### ISSUE TITLE
error in pairing tokens

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#3] opened 2024-12-16 22:03 UTC
user 31 with ID 922628838821859348 (https://discord.com/channels/1294483466079047720/1314629564982624348/1318177304438116453) reported that some tokens can not be paired for swapping.

**Comment by ESSENTIALSAM** [comment] 2024-12-16 22:04
User ID: 922628838821859348 
Link to text: https://discord.com/channels/1294483466079047720/1314629564982624348/1318177304438116453

**Comment by ARitz-Cracker** [comment] 2024-12-16 22:16
duplicate of https://github.com/mace-ag/swaps-app-issues/issues/1

**Closed as not planned** 2024-12-16 22:16 UTC
Labels: duplicate
