### ISSUE TITLE
token swaps error

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#11] opened 2024-12-17 08:40 UTC
user Don11 with uid (1265476096074321970) reported that test token swap from TKA to others is showing error, TKB to TKA success, but to others error. 
text link: https://discord.com/channels/1294483466079047720/1314629564982624348/1318484097382748213

**Comment by ESSENTIALSAM** [comment] 2024-12-17 08:41
uid: 1265476096074321970
text link: https://discord.com/channels/1294483466079047720/1314629564982624348/1318484097382748213

**Comment by ARitz-Cracker** [comment] 2024-12-17 12:24
Seems like a duplicate of #1

**Closed as not planned by ARitz-Cracker** 2024-12-17 12:24 UTC
Labels: duplicate
