### ISSUE TITLE
swap error

### ISSUE THREAD

**Issue by ESSENTIALSAM** [mace-ag/swaps-app-issues#12] opened 2024-12-17 08:47 UTC
user Don11 with uid (1265476096074321970) reported that token  tk abcd swap to eth keeps failing.
text link: https://discord.com/channels/1294483466079047720/1314629564982624348/1318483299869528095

**Comment by ESSENTIALSAM** [comment] 2024-12-17 08:48
uid: 1265476096074321970
text link:  https://discord.com/channels/1294483466079047720/1314629564982624348/1318483299869528095

**Comment by ARitz-Cracker** [comment] 2024-12-17 12:26
Seems like a duplicate of #6

**Closed as not planned by ARitz-Cracker** 2024-12-17 12:26 UTC
Labels: duplicate
